### ISSUE TITLE
Segmentation Error on Windows and WSL

### ISSUE THREAD

**Issue by ocimakamboj** [acycliq/pciSeq#12]
Hi, 

I am running pciseq on a few datasets and it leads to Segmentation Error if I run it on windows or WSL. The same code runs on Linux without any issues. I don't know how to fix it.

**Comment by acycliq** [comment]
This doesnt look very nice to be honest, it sounds like a memory/OS issue. Can you send me the error please? I have a machine with WSL, I will try to run the code there and see if it fails too, but later this evening though....

**Comment by ocimakamboj** [comment]
![image](https://github.com/acycliq/pciSeq/assets/56351128/ea9bbaee-48b0-4dfe-adb6-081fe627b810)

I am attaching a screenshot. The segmentation fault arises even before the iterations start.

**Comment by acycliq** [comment]
yes, doesnt show much. I will run it on WSL and see if I can replicate it. I will get back to you

**Comment by acycliq** [comment]
It works for me on WSL, created a new fresh env and installed the latest pciSeq (v0.0.56) from pip and run it on the demo data without errors. This is what `wsl --status` on the windows prompt returns

```
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 24/10/2022
The Windows Subsystem for Linux kernel can be manually updated with 'wsl --update', but automatic updates cannot occur due to your system settings.
To receive automatic kernel updates, please enable the Windows Update setting: 'Receive updates for other Microsoft products when you update Windows'.
For more information please visit https://aka.ms/wsl2kernel.

Kernel version: 5.10.102.1
```

**Comment by ocimakamboj** [comment]
okay, I created a fresh environment and tried running on the demo data.

1. With python 3.9, there is an error - "Maximum recursion depth exceeded".
2. With python 3.8 it runs successfully. 

It does not seem to be an OS error - I checked my environment in the Linux distribution and it had python 3.8, but the environment causing Segmentation Fault in windows/wsl had python 3.9.

Here is the error I get for Python 3.9 - 
![image](https://github.com/acycliq/pciSeq/assets/56351128/bce2bbc4-6d61-4486-9a2c-03a17d142cf1)
![image](https://github.com/acycliq/pciSeq/assets/56351128/97c538d7-0373-4217-a3ba-15f78c8f946f)

**Comment by acycliq** [comment]
Yes this isn't OS related. Is this happening on WSL, Linux or both?

**Comment by ocimakamboj** [comment]
It happens on both with python 3.9.

**Comment by acycliq** [comment]
Yes, It will crash under python 3.9 but I suspect it has to do more with the numpy and pandas versions than python itself. This is what I am using under python 3.9:
```
np.__version__ = '1.26.0'
pd.__version__ = '2.1.1'
```

Anyways, I have fixed this, will do a release later this evening, Thanks

**Comment by acycliq** [comment]
can you get from pip the latest version, 0.0.59 please? I think it hould wotk now

**Comment by ocimakamboj** [comment]
Hi. It is working now!
