### ISSUE TITLE
Which image did you use for demo?

### ISSUE THREAD

**Issue by YubinXie** [acycliq/pciSeq#3]
Hi Thanks for this awesome data and making it public. I am trying to run the colab and curious that which part of data did you use there? Many thanks!

**Comment by acycliq** [comment]
Hi there

I am not quite sure if I have understood your question. In any case the image is [here](www.acycliq.xyz/ca1/dapi/background_boundaries.tif). It is the dapi image saved as a tiff. Let me know if you need any help.

**Comment by YubinXie** [comment]
Hey, thanks for replying! I saw many files in this link https://figshare.com/s/88a0fc8157aca0c6f0e8?file=13160492 and not sure which one, for example, 3-3 right, is used in the demo.

**Comment by acycliq** [comment]
From that Figshare repo, get `DAPI_4-3.jpg` which is a full coronal section and then keep everything enclosed by the clipping polygon:

`poly = [(13751, 17268), (12739, 15629), (11839, 16237), (11120, 16528), (10333, 16396), (9906, 16105), (9231, 15603), (8916, 15286), (6263, 12987), (6150, 13648), (6150, 14282),(6420, 15074), (6735, 15735), (7072, 16369), (7522, 16977), (8264, 17637), (9119, 18113), (10130, 18324), (10872, 18457), (11997, 18298), (12626, 17981), (13233, 17479), (13751, 17268)]`

That will crop the left part. Then you flip it and you should get what is shown in the demo. Just to clarify also, the coords of a points of the polygon outline are `(x, y)`, ie not` (col, row)`
