### ISSUE TITLE
gene-by-cell matrix

### ISSUE THREAD

**Issue by rocketeer1998** [acycliq/pciSeq#6]
Hi @acycliq , any recommendation about creating a **gene-by-cell expression matrix** without using scRNA-seq data? In other words, I want to assign each ISS spot to the corresponding cell where the value is the raw count number of each spot, which is different from the present expression matrix that stores the processed value.  

The reason for it is that I want to do some scRNA-seq analysis, including dimension reduction, unsupervised clustering, differential expression, etc. But the result is not that good using present expression matrix.

**Comment by acycliq** [comment]
I image you have tried just looking at the segmentation, If a spots is inside the boundaries then assigned it otherwise it is on the background. But you dont need pciSeq for this.
