### ISSUE TITLE
ModuleNotFoundError: No module named 'pciSeq.src.preprocess.imimposemin'

### ISSUE THREAD

**Issue by evenDDDDD** [acycliq/pciSeq#7]
Hi,
When I tried to do cell segmentation on a tif image provided at [https://figshare.com/articles/dataset/CA1_neuron_cell_typing_results_of_pciSeq_probabilistic_cell_typing_by_in_situ_sequencing_/7150760/1](url). And I found I cannot import the function --imposemin.
`from src.preprocess.imimposemin import imimposemin`
`from skimage.color import label2rgb`
`from skimage.util import img_as_ubyte`
`from skimage.morphology import disk`
`import math`
`from matplotlib import pyplot as plt`
`import logging`
`img_url = r"./CA1DapiBoundaries_4-3_right.tif"`
`coo, CellMap_0 = watershed(img_url)`
 `ERROR: ModuleNotFoundError: No module named 'src'`
Then I modified the code appropriately
`from pciSeq.src.preprocess.imimposemin import imimposemin`
  `ERROR: ModuleNotFoundError: No module named 'pciSeq.src.preprocess.imimposemin`
I guess the immposemin package may be missing, can you re-upload it to github?
Sincerely look forward to your reply！！

**Comment by acycliq** [comment]
Yes, this is missing indeed, the function was used for watershed segmentation but it is deprecated now, I should have removed it I would say use some other tool like cellpose if possible

**Comment by evenDDDDD** [comment]
Thanks for the prompt reply, cellpose is indeed a good choice.
