### ISSUE TITLE
Cell Segmentation Algorithm

### ISSUE THREAD

**Issue by Epoch1128** [acycliq/pciSeq#8]
May I ask you for the cell segmentation algorithm to process my samples. Thanks!

**Comment by acycliq** [comment]
We typically use [cellpose](https://github.com/MouseLand/cellpose) for cell segmentation. Hope that helps!

**Comment by Epoch1128** [comment]
It really helps! Thank you for sharing!

**Comment by acycliq** [comment]
Not a problem, let me know if you have any other problems.
